### ISSUE TITLE
Issue with privacy_engine

### ISSUE THREAD

**Issue by acphile** [lxuechen/private-transformers#13]
Thank you for your nice work and code. I have a question about your code for privacy_engine:
https://github.com/lxuechen/private-transformers/blob/main/private_transformers/privacy_utils/privacy_engine.py#L208
For this part, should it be the following?
```
    def get_privacy_spent(_self, **kwargs):
            return _self.privacy_engine.get_privacy_spent(**kwargs)
```
Without return, seemingly it won't record privacy spent for your training in `examples/classification`

**Comment by lxuechen** [comment]
Thanks for catching this! Fixed.
