### ISSUE TITLE
text infilling task

### ISSUE THREAD

**Issue by adam-dziedzic** [lxuechen/private-transformers#34]
Hi All,

Thanks for releasing the code. I was trying to find how the infilling task is implemented, for example, for SST2. I see this part of the code, as shown below, but then it's never used again. Would you point me to the place where the infilling is done for classification?

```
# TODO: Hacky mapping creation. Refactor this in the future.
    #  Currently gets replace if mapping_id and mapping_path is set.
    if data_args.task_name == "sst-2":
        data_args.mapping = "{'0':'terrible','1':'great'}"
    elif data_args.task_name == "mnli":
        data_args.mapping = "{'contradiction': 'no', 'entailment': 'yes', 'neutral': 'maybe'}"
    elif data_args.task_name == "qnli":
        data_args.mapping = "{'not_entailment': 'no', 'entailment': 'yes'}"
    elif data_args.task_name == "qqp":
        data_args.mapping = "{'1': 'yes', '0': 'no'}"  # 1 -- equivalent, 0 -- not equivalent.
    else:
        raise ValueError(f"Unknown task: {data_args.task_name}")
```

**Comment by lxuechen** [comment]
In-filling mode is on when `few_shot_type` is `prompt`. See [this block of code](https://github.com/lxuechen/private-transformers/blob/18ccc4eab7355e4ac96051a82434796f6aa4624b/examples/classification/run_classification.py#L514).

**Comment by adam-dziedzic** [comment]
Okay, this is helpful, thanks!
