### ISSUE TITLE
no metrics: BLEU or Rouge-L

### ISSUE THREAD

**Issue by adam-dziedzic** [lxuechen/private-transformers#36]
For the text-to-table task, there is no code to compute the metrics. When I run your training, there is no possibility of assessing how well it went? What was your approach to compute the metrics?

**Comment by lxuechen** [comment]
The table2text example code should periodically generate samples, with which you could evaluate standard NLG metrics using this [codebase](https://github.com/GEM-benchmark/GEM-metrics). 

This was documented [here](https://github.com/lxuechen/private-transformers/tree/main/examples/table2text).

**Comment by adam-dziedzic** [comment]
Okay, thanks.
