### ISSUE TITLE
Private gradient seemingly has been overwritten by non-private gradient.

### ISSUE THREAD

**Issue by JunyiZhu-AI** [lxuechen/private-transformers#9]
Hi Xuechen, thanks for providing this codebase!

I tried tweaking the code in ```examples/classification``` but the network does not perform as expected. In particular, I tried zeroing out all gradient by this command in ```_step()``` and ```_ghost_step()``` functions in ```privacy_engine.py```:

```
param.grad /= self.batch_size
param.grad.mul_(0)
```
After adding this multiplication the network has been trained as normally. And because with the same seed, the network has been even trained to give out the same eval acc. Could you reproduce this result at your private repo? If it behaves like this, then I suppose that the private gradient has been overwritten by the non-private one.

**Comment by lxuechen** [comment]
Hi, 

I re-ran my code, and I don't get this behavior on the generation task after clearing out the `.grad` attribute as you did. 

Perhaps one thing that could require more care is that the `PrivacyEngine` is installed as part of the package. If the package is not installed via `pip install -e . `, then modifying the cloned codebase would not affect your runs. Happy to discuss a bit more if you have more context.

**Comment by JunyiZhu-AI** [comment]
You're right, I forgot this step. The problem is solved after installing the local package. Thanks for the quick response!

Btw, just for info, there is a typo (qqp -> qpp) that leads to a key error when training with qqp dataset.
https://github.com/lxuechen/private-transformers/blob/81860b38b4d8c951f462703adcadd78b879d9311/examples/classification/run_wrapper.py#L42
I'm closing this issue since the problem is solved.

**Comment by lxuechen** [comment]
Thanks for pointing out the typo. Fixed.
